# Generated by Django 5.2.5 on 2025-08-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataperson',
            name='SNP',
            field=models.CharField(blank=True, max_length=128, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='dataperson',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='dataperson',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='dataperson',
            name='patronymic',
            field=models.CharField(blank=True, max_length=32, verbose_name='Отчество (необязательный параметр)'),
        ),
        migrations.AlterField(
            model_name='dataperson',
            name='surname',
            field=models.CharField(max_length=32, verbose_name='Фамилия'),
        ),
    ]
