# Generated by Django 5.2.5 on 2025-08-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dataperson_snp_alter_dataperson_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataperson',
            name='SNP',
        ),
    ]
