# Generated by Django 5.2.4 on 2025-08-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_todolist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataPerson',
        ),
    ]
